description: this is cloud-config-dev.yml
#server:
#  context-path: /config-test
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: root
