description: this is cloud-config-dev.yml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: root
