profile:dev-yml-1.0

spring:
  datasource:
          name: era
          url: jdbc:mysql://localhost:3306/movie?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
          username: root
          password: root
